sudo: true
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "pypy"
  - "pypy3.5"
  - "pypy3.6"
  - "pypy3.7"
  - "pypy3.8"
  - "pypy3.9"
  - "pypy3"
  - "nightly"

matrix:
  include:
    - python: 2.7
      env: JYTHON=https://search.maven.org/remotecontent?filepath=org/python/jython-installer/2.7.2rc1/jython-installer-2.7.2rc1.jar

before_install:
  - sh .travis_before_install.sh
script:
  - testrunner

jobs:
  allow_failures:
  - python: nightly
