language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3.5"
  - "pypy3"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
script: pytest
