name: Test over CPython

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
jobs:
  setup-versions-from-manifest:
    name: CPython ${{ matrix.python }} @ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04]
        python: ["2.7", "3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python }}

    - name: Show version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest

    - name: Runing tests
      run: |
        python -m pytest -s $(git ls-files 'test*.py')
