name: Test over pypy

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"
jobs:
  setup-versions-from-manifest:
    name: ${{ matrix.pypy}} @ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-20.04]
        pypy: ["pypy-2.7",  "pypy-3.6", "pypy-3.7", "pypy-3.8", "pypy-3.9"]
        exclude:
            - os: macos-latest
              pypy: "pypy-3.6"
            - os: windows-latest
              pypy: "pypy-3.6"
    steps:
    - uses: actions/checkout@v3

    - name: Set up ${{ matrix.pypy }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.pypy }}

    - name: Show version
      run: pypy --version

    - name: Install dependencies
      run: |
        pypy -m pip install --upgrade pip
        pypy -m pip install pytest

    - name: Runing tests
      run: |
        pypy -m pytest -s $(git ls-files 'test*.py')
